output:
  # whether to write data points to the "console" or to a "file", defaults to "console"
  destination: classification_file
  file:
    # the file to write the data points to, defaults to "output.json"
    filename: output.json
    # true if the file should be appended to, false if it should be overwritten, defaults to true
    append: true
    # 输出文件的根目录
    root: /home/just/Documents/data

data:
  header:
    # the user to associate the data points with, defaults to "some-user"
    user-id: the-user

    # 用户产生数量
    user-count: 10000

    # 每个用户组内成员数
    member-in-user-group: 20

    acquisition-provenance:
      # the name of the source of the data points, defaults to "generator"
      source-name: generator

  # data is generated according to these optional default values unless overridden in the measures
  # the earliest date time of the measures to generate, defaults to January 1st, 2014 at noon UTC
  start-date-time: 2017-01-01T03:00:00Z

  # the latest date time of the measures to generate, defaults to January 1st, 2015 at noon UTC
  end-date-time: 2017-01-02T03:00:00Z

  # the mean duration between the effective time frames of consecutive measures, defaults to 24 hours
  # this is specified in ISO8601 duration format, see https://www.ietf.org/rfc/rfc3339.txt page 12
  mean-inter-point-duration: PT24h

  # true if measures having effective time frames at night should be suppressed, defaults to false
  # a measure is considered to occur at night if its effective time frame is after 23:00 or before 6:00
  suppress-night-time-measures: false

  # true if measures want to have a cycle loop with specific trend(e.g. linear polynomial),defaults to false
  # false means trend is steady(normal distribution of N(start+end/2,deviation))
  daily : false
  # a list of measure generation requests, with the following structure
  #
  # - generator: body-weight             # the name of the measure generator to use, as defined by the generator
  #   containers:                            # a map of linear containers and trend definitions
  #     ? weight-in-kg                   # a trend key, as defined by the generator
  #     : start-date-time: ...           # override for the defaults listed above
  #       end-date-time: ...
  #       mean-inter-point-duration: ...
  #       suppress-night-time-measures: ...
  #       minimum-value: 50              # a lower bound on the value, default none
  #       maximum-value: 65              # an upper bound on the value, default none
  #       standard-deviation: 0.1        # the standard deviation of the value from the interpolated mean, default 0
  #       trends:
  #       - shape: linear                # the shape this trend looks like
  #         start-moment: 12                  # the clock(between 0~24) the trend starts with
  #         end-moment: 18                  # the clock the trend ends with
  #         start-value: 60                  # the value the trend starts with
  #         end-value: 80                  # the value the trend ends with
  #
  # see the documentation at https://github.com/openmhealth/sample-data-generator for more information
  # by default, no data is generated; uncomment and modify the following configuration as needed

  measure-generation-requests:
  - generator: blood-pressure
    mean-inter-point-duration: PT1m
    daily : true
    containers:
      ? systolic-in-mmhg
      : minimum-value: 100
        maximum-value: 140
        standard-deviation: 3
        trends:
        - shape : linear
          start-moment: 3
          end-moment : 9
          start-value : 105
          end-value: 125
        - shape : linear
          start-moment: 9
          end-moment : 12
          start-value : 125
          end-value: 110
        - shape : linear
          start-moment: 12
          end-moment : 17
          start-value : 110
          end-value: 125
        - shape: linear
          start-moment : 17
          end-moment: 3
          start-value : 125
          end-value : 105
      ? diastolic-in-mmhg
      : minimum-value: 60
        maximum-value: 90
        standard-deviation: 3
        trends:
        - shape : linear
          start-moment: 3
          end-moment : 9
          start-value : 65
          end-value: 85
        - shape : linear
          start-moment: 9
          end-moment : 12
          start-value : 85
          end-value: 70
        - shape : linear
          start-moment: 12
          end-moment : 17
          start-value : 70
          end-value: 80
        - shape: linear
          start-moment : 17
          end-moment: 3
          start-value : 80
          end-value : 65

#
#  - generator: body-weight
#    containers:
#      ? weight-in-kg
#      : start-value: 55
#        end-value: 60
#        minimum-value: 50
#        maximum-value: 65
#        standard-deviation: 0.1
#
#  - generator: body-height
#    containers:
#      ? height-in-meters
#      : start-value: 1.75
#        end-value: 1.75
#        minimum-value: 1.745
#        maximum-value: 1.755
#        standard-deviation: 0
#
  - generator: step-count
    mean-inter-point-duration: PT30m
    suppress-night-time-measures: true
    containers:
      ? duration-in-seconds
      : minimum-value: 10
        maximum-value: 1800
        standard-deviation: 50
        trends:
        - start-value: 300
          end-value: 1500
      ? steps-per-minute
      : minimum-value: 30
        maximum-value: 125
        standard-deviation: 15
        trends:
        - start-value: 90
          end-value: 90

#  - generator: physical-activity
#    containers:
#      ? duration-in-seconds
#      : start-value: 1800
#        end-value: 1800
#        minimum-value: 300
#        maximum-value: 2400
#        standard-deviation: 600
#      ? distance-in-meters
#      : start-value: 5000
#        end-value: 5000
#        minimum-value: 500
#        maximum-value: 20000
#        standard-deviation: 1000

  - generator: heart-rate
    mean-inter-point-duration: PT1m
    containers:
      ? rate-in-beats-per-minute
      : minimum-value: 60
        maximum-value: 200
        standard-deviation: 10
        trends:
        - start-value: 80
          end-value: 130
#  - generator: minutes-moderate-activity
#    containers:
#      ? minutes
#      : start-value: 30
#        end-value: 30
#        minimum-value: 5
#        maximum-value: 120
#        standard-deviation: 20
#
  - generator: body-fat-percentage
    mean-inter-point-duration: PT30m
    containers:
      ? percentage
      : minimum-value: 28
        maximum-value: 32
        standard-deviation: 0.25
        trends:
        - start-value: 30
          end-value: 30


#
#  - generator: ambient-temperature
#    containers:
#      ? temperature-in-c
#      : start-value: 22
#        end-value: 22
#        minimum-value: 18
#        maximum-value: 26
#        standard-deviation: 1
#
#  - generator: blood-glucose
#    containers:
#      ? glucose-in-mg-per-dl
#      : start-value: 90
#        end-value: 100
#        minimum-value: 85
#        maximum-value: 140
#        standard-deviation: 5
#
  - generator: body-temperature
    mean-inter-point-duration: PT1m
    containers:
      ? temperature-in-c
      : minimum-value: 36.4
        maximum-value: 38
        standard-deviation: 0.3
        trends:
        - start-value: 36.8
          end-value: 36.8

  - generator: sleep-duration
    containers:
      ? duration-in-hours
      : minimum-value: 4
        maximum-value: 12
        standard-deviation: 0.75
        trends:
        - start-value: 8
          end-value: 8